<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.Master" AutoEventWireup="true" CodeBehind="Patients.aspx.cs" Inherits="HospitalSystem.Patients.Patients" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="m-2">

        <div class="w-100 ">

            <a href="UserManagement.aspx" style="text-decoration: none;">
                <h2 class="text-center fw-bold mb-4 py-2 border-bottom shadow-sm bg-light text-success">User Management</h2>
            </a>
            <!-- Toggle Button -->
            <div class="d-flex justify-content-between align-items-center flex-wrap bg-light px-3 rounded shadow-sm ">

                <asp:Button ID="btnToggleView" runat="server" CssClass="btn btn-primary mb-3 mt-4"
                    Text="Show Deleted Patients" OnClick="btnToggleView_Click" />
            </div>

            <!-- Add User and Search Section -->
            <div class="d-flex justify-content-between align-items-center flex-wrap bg-light p-3 rounded shadow-sm mb-3">
                <!-- Search Box & Buttons (Left Side) -->
                <div class="d-flex flex-grow-1 me-3 align-items-stretch">
                    <telerik:RadTextBox ID="txtSearch" runat="server" EmptyMessage="🔍 Search by Full Name..."
                        CssClass="form-control shadow-sm py-2" Width="75%" />

                    <telerik:RadButton ID="btnSearch" runat="server" Text="🔍 Search" CssClass="btn btn-primary ms-2 px-3"
                        OnClick="btnSearch_Click" />

                    <telerik:RadButton ID="btnResetSearch" runat="server" Text="🔄 Reset" CssClass="btn btn-secondary ms-2 px-3"
                        OnClick="btnResetSearch_Click" />
                </div>
            </div>

            <!-- Active Patients Grid -->
            <div class="w-100 border shadow-sm p-3">
                <asp:Panel ID="pnlActivePatients" runat="server">
                    <telerik:RadGrid ID="RadGridActive" runat="server" AutoGenerateColumns="False" AllowPaging="True"
                        AutoGenerateDeleteColumn="True" CellSpacing="-1" GridLines="Both"
                        OnDeleteCommand="RadGridActive_DeleteCommand" AutoGenerateEditColumn="True" OnUpdateCommand="RadGridActive_UpdateCommand"
                        OnNeedDataSource="RadGridActive_NeedDataSource">
                        <MasterTableView DataKeyNames="PatientID">
                            <Columns>
                                <telerik:GridBoundColumn DataField="PatientID" HeaderText="Patient ID" UniqueName="PatientID" ReadOnly="true" />
                                <telerik:GridTemplateColumn HeaderText="Patient Name" UniqueName="FullNameColumn">
                                    <ItemTemplate>
                                        <asp:HyperLink ID="lnkPatientHistory" runat="server"
                                            NavigateUrl='<%# "PatientHistory.aspx?PatientID=" + Eval("PatientID") %>'
                                            Text='<%# Eval("FullName") %>' CssClass="text-primary">
                                        </asp:HyperLink>
                                    </ItemTemplate>
                                    <EditItemTemplate>
                                        <telerik:RadTextBox ID="txtFullName" runat="server" Text='<%# Bind("FullName") %>' CssClass="form-control" />
                                    </EditItemTemplate>
                                </telerik:GridTemplateColumn>

                                <telerik:GridBoundColumn DataField="Phone" HeaderText="Patient Phone" UniqueName="Phone" />

                            </Columns>
                            <EditFormSettings>
                                <EditColumn ShowNoSortIcon="False"></EditColumn>
                            </EditFormSettings>
                        </MasterTableView>
                        <HeaderStyle BackColor="#23408E" ForeColor="#ED1B24" />
                    </telerik:RadGrid>
                </asp:Panel>
            </div>

            <!-- Deleted Patients Grid -->
            <div class="w-100 border shadow-sm p-3">
                <asp:Panel ID="pnlDeletedPatients" runat="server" Visible="false">
                    <telerik:RadGrid ID="RadGridDeleted" runat="server" AutoGenerateColumns="False" AllowPaging="True"
                        CellSpacing="-1" GridLines="Both" OnNeedDataSource="RadGridDeleted_NeedDataSource" OnItemCommand="RadGridDeleted_ItemCommand">
                        <MasterTableView DataKeyNames="PatientID">
                            <Columns>
                                <telerik:GridBoundColumn DataField="PatientID" HeaderText="Patient ID" UniqueName="PatientID" />
                                <telerik:GridBoundColumn DataField="PatientFullName" HeaderText="Patient Name" UniqueName="PatientFullName" />
                                <telerik:GridBoundColumn DataField="DeletedBy" HeaderText="Deleted By" UniqueName="UserFullName" />
                                <telerik:GridBoundColumn DataField="UserFullName" HeaderText="User Name" UniqueName="UserFullName" />
                                <telerik:GridBoundColumn DataField="DeletedAt" HeaderText="Deleted At" UniqueName="DeletedAt" DataFormatString="{0:MM/dd/yyyy}" />
                                <telerik:GridTemplateColumn HeaderText="Restore User" UniqueName="RestoreColumn">
                                    <ItemStyle HorizontalAlign="Center" Width="50px" />
                                    <ItemTemplate>
                                        <asp:Button ID="btnRestorePatient" runat="server" Text="&#10084;"
                                            ForeColor="Red" CssClass="btn text-center" CommandName="RestorePatient"
                                            CommandArgument='<%# Eval("PatientID") %>' />
                                    </ItemTemplate>
                                </telerik:GridTemplateColumn>
                            </Columns>
                            <EditFormSettings>
                                <EditColumn ShowNoSortIcon="False"></EditColumn>
                            </EditFormSettings>
                        </MasterTableView>
                        <HeaderStyle BackColor="#23408E" ForeColor="#ED1B24" />
                    </telerik:RadGrid>
                </asp:Panel>
            </div>

            <!-- Patient Registration Form -->
            <div class="w-100 border shadow-sm p-3 mt-4">
                <h4 class="mb-3 text-center">Add New Patient</h4>

                <!-- First Row -->
                <div class="row">
                    <div class="col-md-3 mb-3">
                        <telerik:RadTextBox ID="txtFirstName" runat="server" CssClass="form-control" EmptyMessage="First Name..." />
                    </div>
                    <div class="col-md-3 mb-3">
                        <telerik:RadTextBox ID="txtLastName" runat="server" CssClass="form-control" EmptyMessage="Last Name..." />
                    </div>
                    <div class="col-md-3 mb-3">
                        <telerik:RadTextBox ID="txtDOB" runat="server" CssClass="form-control" EmptyMessage="YYYY-MM-DD..." />
                    </div>
                    <div class="col-md-3 mb-3">
                        <telerik:RadTextBox ID="txtGender" runat="server" CssClass="form-control" EmptyMessage="Gender..." />
                    </div>
                </div>

                <!-- Second Row -->
                <div class="row">
                    <div class="col-md-3 mb-3">
                        <telerik:RadTextBox ID="txtPhone" runat="server" CssClass="form-control" EmptyMessage="Phone..." />
                    </div>
                    <div class="col-md-3 mb-3">
                        <telerik:RadTextBox ID="txtEmail" runat="server" CssClass="form-control" EmptyMessage="Email..." />
                    </div>
                    <div class="col-md-6 mb-3">
                        <telerik:RadTextBox ID="txtAddress" runat="server" CssClass="form-control" EmptyMessage="Address..." />
                    </div>
                </div>

                <!-- Centered Telerik Button with Bottom Margin -->
                <div class="d-flex justify-content-center mb-4">
                    <telerik:RadButton ID="btnAddPatient" runat="server" Class="btn btn-success" Style="background-color: #259843; color: white;"
                        ButtonType="SkinnedButton" Text="Add Patient" OnClick="btnAddPatient_Click" />
                </div>
            </div>
        </div>


    </div>
</asp:Content>
