<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.Master" AutoEventWireup="true" CodeBehind="Patients.aspx.cs" Inherits="HospitalSystem.Patients.Patients" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="container mt-4">
        <!-- Bootstrap Container -->

        <!-- Wrapper for Search Bar & Grid -->
        <div class="w-100 p-3">
            <!-- Full Width & Padding -->

            <!-- Toggle Button -->
            <asp:Button ID="btnToggleView" runat="server" CssClass="btn btn-primary mb-3"
                Text="Show Deleted Patients" OnClick="btnToggleView_Click" />

            <!-- Search Box -->
            <telerik:RadTextBox ID="txtSearch" runat="server" AutoPostBack="true" OnTextChanged="txtSearch_TextChanged"
                EmptyMessage="Search by Full Name..." CssClass="form-control w-100 p-3 mb-3" Width="100%" />

            <!-- Active Patients Grid -->
            <div class="w-100 border shadow-sm p-3">
                <asp:Panel ID="pnlActivePatients" runat="server">
                    <telerik:RadGrid ID="RadGridActive" runat="server" AutoGenerateColumns="False" AllowPaging="True"
                        AutoGenerateDeleteColumn="True" CellSpacing="-1" GridLines="Both"
                        OnDeleteCommand="RadGridActive_DeleteCommand" AutoGenerateEditColumn="True" OnUpdateCommand="RadGridActive_UpdateCommand"
                         OnNeedDataSource="RadGridActive_NeedDataSource">
                        <MasterTableView DataKeyNames="PatientID">
                            <Columns>
                                <telerik:GridBoundColumn DataField="PatientID" HeaderText="Patient ID" UniqueName="PatientID" />
                                <telerik:GridBoundColumn DataField="FullName" HeaderText="Patient Name" UniqueName="FullName" />
                                <telerik:GridBoundColumn DataField="Phone" HeaderText="Patient Phone" UniqueName="Phone" />
                                <telerik:GridButtonColumn CommandName="DeletePatient" Text="&#10060;" HeaderText="Delete"
                                    UniqueName="DeleteColumn" ButtonType="LinkButton" ItemStyle-CssClass="text-center" />
                            </Columns>
                            <EditFormSettings>
                                <EditColumn ShowNoSortIcon="False"></EditColumn>
                            </EditFormSettings>
                        </MasterTableView>
                        <HeaderStyle BackColor="#23408E" ForeColor="#ED1B24" />
                    </telerik:RadGrid>
                </asp:Panel>
            </div>

            <!-- Deleted Patients Grid -->
            <div class="w-100 border shadow-sm p-3">
                <asp:Panel ID="pnlDeletedPatients" runat="server" Visible="false">
                    <telerik:RadGrid ID="RadGridDeleted" runat="server" AutoGenerateColumns="False" AllowPaging="True"
                        CellSpacing="-1" GridLines="Both"  OnNeedDataSource="RadGridDeleted_NeedDataSource">
                        <MasterTableView DataKeyNames="PatientID">
                            <Columns>
                                <telerik:GridBoundColumn DataField="PatientID" HeaderText="Patient ID" UniqueName="PatientID" />
                                <telerik:GridBoundColumn DataField="PatientFullName" HeaderText="Patient Name" UniqueName="PatientFullName" />
                                <telerik:GridBoundColumn DataField="DeletedBy" HeaderText="Deleted By" UniqueName="UserFullName" />
                                <telerik:GridBoundColumn DataField="UserFullName" HeaderText="User Name" UniqueName="UserFullName" />
                                <telerik:GridBoundColumn DataField="DeletedAt" HeaderText="Deleted At" UniqueName="DeletedAt" DataFormatString="{0:MM/dd/yyyy}" />
                            </Columns>
                            <EditFormSettings>
                                <EditColumn ShowNoSortIcon="False"></EditColumn>
                            </EditFormSettings>
                        </MasterTableView>
                        <HeaderStyle BackColor="#23408E" ForeColor="#ED1B24" />
                    </telerik:RadGrid>
                </asp:Panel>
            </div>

        </div>

    </div>
</asp:Content>
