<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.Master" AutoEventWireup="true" CodeBehind="Departments.aspx.cs" Inherits="HospitalSystem.Doctors.Departments" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">

<telerik:RadGrid ID="RadGrid1" runat="server" AllowFilteringByColumn="True" AllowPaging="True"
    AllowSorting="True" AutoGenerateDeleteColumn="True" AutoGenerateEditColumn="True"
    OnItemDataBound="RadGrid1_ItemDataBound" OnNeedDataSource="RadGrid1_NeedDataSource"
    OnItemCommand="RadGrid1_ItemCommand"  ShowFooter="True" Skin="Silk" OnInsertCommand="RadGrid1_ItemInsert" OnDeleteCommand="RadGrid1_DeleteCommand" 
OnUpdateCommand="RadGrid1_UpdateCommand" EnableHierarchyExpandAll="True">
    
    <GroupingSettings CollapseAllTooltip="Collapse all groups"></GroupingSettings>

    <ClientSettings>
        <Scrolling AllowScroll="True" UseStaticHeaders="True" />
    </ClientSettings>

    <MasterTableView AutoGenerateColumns="False" DataKeyNames="DepartmentID" ShowFooter="False"
        AllowAutomaticDeletes="true" AllowAutomaticUpdates="true" AllowAutomaticInserts="True"  InsertItemPageIndexAction="ShowItemOnFirstPage" CommandItemDisplay="Top">

         
<RowIndicatorColumn ShowNoSortIcon="False"></RowIndicatorColumn>

<ExpandCollapseColumn ShowNoSortIcon="False"></ExpandCollapseColumn>


        <Columns>
            <telerik:GridBoundColumn DataField="DepartmentName" HeaderText="Department Name" UniqueName="DepartmentName" />

            <telerik:GridTemplateColumn HeaderText="Assign Doctor">
                <ItemTemplate>
                    <asp:DropDownList ID="ddlDoctors" runat="server" AppendDataBoundItems="true">
                        <asp:ListItem Text="Select Doctor" Value="" />
                    </asp:DropDownList>

                    <asp:Button ID="btnAssignDoctor" runat="server" Text="Assign"
                        CommandName="AssignDoctor" CommandArgument='<%# Eval("DepartmentID") %>' />
                </ItemTemplate>
            </telerik:GridTemplateColumn>

            <telerik:GridBoundColumn DataField="DepartmentID" HeaderText="Department ID"
                ReadOnly="True" UniqueName="DepartmentID" Visible="False" />
            <telerik:GridTemplateColumn HeaderText="Doctors">
                <ItemTemplate>
                    <asp:Repeater ID="rptDoctors" runat="server">
                        <ItemTemplate>
                            <div>
                                <strong><%# Eval("FullName") %></strong> - <%# Eval("SpecialityName") %>
                                <asp:Button ID="btnUnassignDoctor" runat="server" Text="Unassign"
                                CommandName="UnassignDoctor" OnCommand="btnUnassignDoctor_Command" CommandArgument='<%# Eval("DoctorID") %>' CssClass="unassign-btn" />
                            </div>
                        </ItemTemplate>
                    </asp:Repeater>
                </ItemTemplate>
            </telerik:GridTemplateColumn>
        </Columns>

<EditFormSettings>
<EditColumn ShowNoSortIcon="False"></EditColumn>
</EditFormSettings>
    </MasterTableView>
</telerik:RadGrid>
    </asp:Content>