<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.Master" AutoEventWireup="true" CodeBehind="Departments.aspx.cs" Inherits="HospitalSystem.Doctors.Departments" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
  <a href="Deparments.aspx" style="text-decoration: none;">
        <h2 class="text-center fw-bold mb-4 py-2 border-bottom shadow-sm bg-light text-success">Department Management</h2>
    </a>
    <div class="d-flex justify-content-between align-items-center flex-wrap bg-light px-3 rounded shadow-sm ">

     <asp:Button ID="btnToggleView" runat="server" CssClass="btn btn-primary mb-3 mt-4"
         Text="Show Deleted Deparments" OnClick="btnToggleView_Click" />
    </div>
<asp:panel id="ActiveDeparment" runat="server">
<telerik:RadGrid ID="RadGrid1" runat="server" AllowPaging="True"
    AllowSorting="True" AutoGenerateDeleteColumn="True" AutoGenerateEditColumn="True"
    OnItemDataBound="RadGrid1_ItemDataBound" OnNeedDataSource="RadGrid1_NeedDataSource"
    OnItemCommand="RadGrid1_ItemCommand"  ShowFooter="True" Skin="Bootstrap" OnInsertCommand="RadGrid1_ItemInsert" OnDeleteCommand="RadGrid1_DeleteCommand" 
OnUpdateCommand="RadGrid1_UpdateCommand" EnableHierarchyExpandAll="True"  >
    
    <GroupingSettings CollapseAllTooltip="Collapse all groups"></GroupingSettings>

    <ClientSettings>
        <Scrolling AllowScroll="True" UseStaticHeaders="True" />
    </ClientSettings>

    <MasterTableView AutoGenerateColumns="False" DataKeyNames="DepartmentID" ShowFooter="False"
        AllowAutomaticDeletes="true" AllowAutomaticUpdates="true" AllowAutomaticInserts="True"  InsertItemPageIndexAction="ShowItemOnFirstPage" CommandItemDisplay="Top">

         
<RowIndicatorColumn ShowNoSortIcon="False"></RowIndicatorColumn>

<ExpandCollapseColumn ShowNoSortIcon="False"></ExpandCollapseColumn>


        <Columns>
            <telerik:GridBoundColumn DataField="DepartmentName" HeaderText="Department Name" UniqueName="DepartmentName" />

            <telerik:GridTemplateColumn HeaderText="Assign Doctor" AllowFiltering="False">
                <ItemTemplate>
                    <div class="assign-doctor-container">
                        <asp:DropDownList ID="ddlDoctors" runat="server" AppendDataBoundItems="true" CssClass="doctor-dropdown">
                            <asp:ListItem Text="Select Doctor" Value="" />
                        </asp:DropDownList>

                        <asp:Button ID="btnAssignDoctor" runat="server" Text="Assign"
                            CommandName="AssignDoctor" CommandArgument='<%# Eval("DepartmentID") %>' CssClass="assign-btn" />
                    </div>
                </ItemTemplate>
            </telerik:GridTemplateColumn>

            <telerik:GridBoundColumn DataField="DepartmentID" HeaderText="Department ID"
                ReadOnly="True" UniqueName="DepartmentID" Visible="False" AllowFiltering="False" />
                <telerik:GridTemplateColumn HeaderText="Doctors -- Speciality" AllowFiltering="False">
                    <ItemTemplate>
                        <asp:Repeater ID="rptDoctors" runat="server">
                            <ItemTemplate>
                                <div class="repeater-item">
                                    <div class="doctor-info">
                                        <strong><%# Eval("FullName") %></strong> - 
                                        <span class="speciality"><%# Eval("SpecialityName") %></span>
                                    </div>
                                    <asp:Button ID="btnUnassignDoctor" runat="server" Text="Unassign"
                                        CommandName="UnassignDoctor" OnCommand="btnUnassignDoctor_Command" 
                                        CommandArgument='<%# Eval("DoctorID") %>' CssClass="unassign-btn" />
                                </div>
                            </ItemTemplate>
                        </asp:Repeater>
                    </ItemTemplate>
                </telerik:GridTemplateColumn>
        </Columns>

<EditFormSettings>
<EditColumn ShowNoSortIcon="False"></EditColumn>
</EditFormSettings>
        <HeaderStyle BackColor="Green" ForeColor="White" />
    </MasterTableView>
</telerik:RadGrid>
    </asp:panel>

    <asp:panel id="DeletedDepartment" runat="server" Visible="false">
        <telerik:RadGrid ID="RadGridDeleted" runat="server" AutoGenerateColumns="False" AllowPaging="True"
                 CellSpacing="-1" GridLines="Both" OnNeedDataSource="RadGridDeleted_NeedDataSource" >
                 <MasterTableView DataKeyNames="DepartmentID">
                     <Columns>
                        
                         <telerik:GridBoundColumn DataField="DepartmentName" HeaderText="Department Name" UniqueName="DepartmentName" />
              
                           
                     
                     </Columns>
                     <EditFormSettings>
                         <EditColumn ShowNoSortIcon="False"></EditColumn>
                     </EditFormSettings>
                 </MasterTableView>
                 <HeaderStyle BackColor="#23408E" ForeColor="#ED1B24" />
             </telerik:RadGrid>
    </asp:panel>
    </asp:Content>