<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.Master" AutoEventWireup="true" CodeBehind="Departments.aspx.cs" Inherits="HospitalSystem.Doctors.Departments" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
  <a href="Departments.aspx" style="text-decoration: none;">
        <h2 class="text-center fw-bold mb-4 py-2 border-bottom shadow-sm bg-light text-success">Department Management</h2>
    </a>
    <div class="d-flex justify-content-between align-items-center flex-wrap bg-light px-3 rounded shadow-sm ">

     <asp:Button ID="btnToggleView" runat="server" CssClass="btn btn-primary mb-3 mt-4"
         Text="Show Deleted Deparments" OnClick="btnToggleView_Click" />
    </div>
    <div class="d-flex justify-content-between align-items-center flex-wrap bg-light p-3 rounded shadow-sm mb-3">
    <!-- Search Box & Buttons (Left Side) -->
    <div class="d-flex flex-grow-1 me-3 align-items-stretch">
        <telerik:RadTextBox ID="txtSearch" runat="server" EmptyMessage="🔍 Search by Full Name..."
            CssClass="form-control shadow-sm py-2" Width="40%" />

        <telerik:RadButton ID="btnSearch" runat="server" Text="🔍 Search" CssClass="btn btn-primary ms-2 px-3"
            OnClick="btnSearch_Click" />

        <telerik:RadButton ID="btnResetSearch" runat="server" Text="🔄 Reset" CssClass="btn btn-secondary ms-2 px-3"
            OnClick="btnResetSearch_Click" />
    </div>

    </div>
<asp:panel id="ActiveDeparment" runat="server">
<telerik:RadGrid ID="RadGrid1" runat="server" AllowPaging="True"
    AllowSorting="True" AutoGenerateDeleteColumn="True" AutoGenerateEditColumn="True"
    OnItemDataBound="RadGrid1_ItemDataBound" OnNeedDataSource="RadGrid1_NeedDataSource"
    OnItemCommand="RadGrid1_ItemCommand"  ShowFooter="True" Skin="Bootstrap" OnInsertCommand="RadGrid1_ItemInsert" OnDeleteCommand="RadGrid1_DeleteCommand" 
OnUpdateCommand="RadGrid1_UpdateCommand" EnableHierarchyExpandAll="True"  >
    
    <GroupingSettings CollapseAllTooltip="Collapse all groups"></GroupingSettings>

    <ClientSettings>
        <Scrolling AllowScroll="True" UseStaticHeaders="True" />
    </ClientSettings>

    <MasterTableView AutoGenerateColumns="False" DataKeyNames="DepartmentID" ShowFooter="False"
        AllowAutomaticDeletes="true" AllowAutomaticUpdates="true" AllowAutomaticInserts="True"  InsertItemPageIndexAction="ShowItemOnFirstPage" CommandItemDisplay="Top">

         
<RowIndicatorColumn ShowNoSortIcon="False"></RowIndicatorColumn>

<ExpandCollapseColumn ShowNoSortIcon="False"></ExpandCollapseColumn>


        <Columns>
            <telerik:GridBoundColumn DataField="DepartmentName" HeaderText="Department Name" UniqueName="DepartmentName" />

            <telerik:GridTemplateColumn HeaderText="Assign Doctor" AllowFiltering="False">
                <ItemTemplate>
                    <div class="assign-doctor-container">
                        <asp:DropDownList ID="ddlDoctors" runat="server" AppendDataBoundItems="true" CssClass="doctor-dropdown">
                            <asp:ListItem Text="Select Doctor" Value="" />
                        </asp:DropDownList>

                        <asp:Button ID="btnAssignDoctor" runat="server" Text="Assign"
                            CommandName="AssignDoctor" CommandArgument='<%# Eval("DepartmentID") %>' CssClass="assign-btn" />
                    </div>
                </ItemTemplate>
            </telerik:GridTemplateColumn>

            <telerik:GridBoundColumn DataField="DepartmentID" HeaderText="Department ID"
                ReadOnly="True" UniqueName="DepartmentID" Visible="False" AllowFiltering="False" />
                <telerik:GridTemplateColumn HeaderText="Doctors -- Speciality" AllowFiltering="False">
                    <ItemTemplate>
                        <asp:Repeater ID="rptDoctors" runat="server">
                            <ItemTemplate>
                                <div class="repeater-item">
                                    <div class="doctor-info">
                                        <strong><%# Eval("FullName") %></strong> - 
                                        <span class="speciality"><%# Eval("SpecialityName") %></span>
                                    </div>
                                    <asp:Button ID="btnUnassignDoctor" runat="server" Text="Unassign"
                                        CommandName="UnassignDoctor" OnCommand="btnUnassignDoctor_Command" 
                                        CommandArgument='<%# Eval("DoctorID") %>' CssClass="unassign-btn" />
                                </div>
                            </ItemTemplate>
                        </asp:Repeater>
                    </ItemTemplate>
                </telerik:GridTemplateColumn>
        </Columns>

<EditFormSettings>
<EditColumn ShowNoSortIcon="False"></EditColumn>
</EditFormSettings>
        <HeaderStyle BackColor="Green" ForeColor="White" />
    </MasterTableView>
</telerik:RadGrid>
    </asp:panel>

    <asp:panel id="DeletedDepartment" runat="server" Visible="false">
        <telerik:RadGrid ID="RadGridDeleted" runat="server" AutoGenerateColumns="False" AllowPaging="True"
                 CellSpacing="-1" GridLines="Both" OnNeedDataSource="RadGridDeleted_NeedDataSource" OnDeleteCommand="RadGridDeletedUsers_DeleteCommand">
                 <MasterTableView DataKeyNames="DepartmentID">
                     <Columns>
                        
                         <telerik:GridBoundColumn DataField="DepartmentName" HeaderText="Department Name" UniqueName="DepartmentName" />


                         <telerik:GridTemplateColumn HeaderText="Restore" UniqueName="RestoreColumn">
                             <HeaderStyle HorizontalAlign="Center" />
                             <ItemStyle HorizontalAlign="Center" Width="50px" />
                             <ItemTemplate>
                                 <div class="d-flex justify-content-center">
                                     <asp:LinkButton ID="btnRestore" runat="server" CommandName="Delete" CssClass="btn btn-link text-success">
                 <svg fill="#25ad52" width="24" height="24" version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 342.5 342.5" xml:space="preserve" stroke="#25ad52" transform="rotate(90)matrix(1, 0, 0, -1, 0, 0)" stroke-width="0.003425"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"> <path d="M254.37,22.255c-1.161-0.642-2.53-0.795-3.803-0.428c-1.274,0.367-2.35,1.226-2.992,2.387l-21.758,39.391 c-1.335,2.417-0.458,5.459,1.96,6.794C264.616,90.748,287.5,129.495,287.5,171.52c0,63.649-51.782,115.431-115.431,115.431 S56.638,235.169,56.638,171.52c0-23.888,7.557-47.427,21.382-66.897l34.478,34.478c1.338,1.337,3.315,1.806,5.109,1.21 c1.795-0.596,3.101-2.152,3.374-4.024L139.963,6.271c0.228-1.563-0.295-3.141-1.412-4.258c-1.117-1.117-2.7-1.639-4.258-1.412 L4.278,19.584c-1.872,0.273-3.428,1.579-4.023,3.374c-0.596,1.795-0.127,3.772,1.21,5.109l37.292,37.292 C14.788,95.484,1.638,133,1.638,171.52c0,93.976,76.455,170.431,170.431,170.431c93.976,0,170.431-76.455,170.431-170.431 C342.5,109.478,308.731,52.283,254.37,22.255z"></path> </g></svg>
                                     </asp:LinkButton>
                                 </div>
                             </ItemTemplate>
                         </telerik:GridTemplateColumn>
                     </Columns>
                     <EditFormSettings>
                         <EditColumn ShowNoSortIcon="False"></EditColumn>
                     </EditFormSettings>
                 </MasterTableView>
                 <HeaderStyle BackColor="Green" ForeColor="White" />
             </telerik:RadGrid>
    </asp:panel>
    </asp:Content>