<%@ Page Title="User Management" Language="C#" MasterPageFile="~/MasterPage.Master" AutoEventWireup="true" CodeBehind="UserManagement.aspx.cs" Inherits="HospitalSystem.Users.UserManagement" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <h2 style="text-align: center; font-size: 22px; font-weight: bold; margin-top: 15px; margin-bottom: 15px">User Management</h2>

    <telerik:RadGrid ID="RadGrid1" runat="server" AllowAutomaticDeletes="True" AllowAutomaticInserts="True"
        AllowAutomaticUpdates="True" AllowFilteringByColumn="True" AllowPaging="True" AllowSorting="True"
        AutoGenerateDeleteColumn="True" AutoGenerateEditColumn="True" DataSourceID="UserDataSource" ShowFooter="True" CssClass="mx-2" OnDeleteCommand="RadGrid1_DeleteCommand">

        <GroupingSettings CollapseAllTooltip="Collapse all groups"></GroupingSettings>

        <ClientSettings>
            <Scrolling AllowScroll="True" UseStaticHeaders="True" />
        </ClientSettings>

        <MasterTableView AutoGenerateColumns="False" DataKeyNames="UserID" DataSourceID="UserDataSource">
            <RowIndicatorColumn ShowNoSortIcon="False"></RowIndicatorColumn>
            <ExpandCollapseColumn ShowNoSortIcon="False"></ExpandCollapseColumn>
            <Columns>
                <telerik:GridBoundColumn DataField="UserID" DataType="System.Int32" HeaderText="UserID"
                    ReadOnly="True" UniqueName="UserID" SortExpression="UserID">
                </telerik:GridBoundColumn>

                <telerik:GridBoundColumn DataField="Username" HeaderText="Username"
                    SortExpression="Username" UniqueName="Username">
                </telerik:GridBoundColumn>

                <telerik:GridBoundColumn DataField="PasswordHash" HeaderText="PasswordHash"
                    SortExpression="PasswordHash" UniqueName="PasswordHash">
                </telerik:GridBoundColumn>

                <telerik:GridBoundColumn DataField="FullName" HeaderText="FullName"
                    SortExpression="FullName" UniqueName="FullName">
                </telerik:GridBoundColumn>

                <telerik:GridBoundColumn DataField="Email" HeaderText="Email"
                    SortExpression="Email" UniqueName="Email">
                </telerik:GridBoundColumn>

                <telerik:GridBoundColumn DataField="Phone" HeaderText="Phone"
                    SortExpression="Phone" UniqueName="Phone">
                </telerik:GridBoundColumn>

                <telerik:GridBoundColumn DataField="RoleID" DataType="System.Int32"
                    HeaderText="RoleID" SortExpression="RoleID" UniqueName="RoleID" FilterControlAltText="Filter RoleID column">
                </telerik:GridBoundColumn>

                <telerik:GridBoundColumn DataField="CreatedAt" DataType="System.DateTime"
                    HeaderText="CreatedAt" SortExpression="CreatedAt" UniqueName="CreatedAt">
                </telerik:GridBoundColumn>

                <telerik:GridBoundColumn DataField="RoleName" HeaderText="RoleName"
                    SortExpression="RoleName" UniqueName="RoleName">
                </telerik:GridBoundColumn>

                <telerik:GridBoundColumn DataField="IsLocked" DataType="System.Boolean"
                    HeaderText="Is Locked" SortExpression="IsLocked" UniqueName="IsLocked">
                </telerik:GridBoundColumn>
            </Columns>

            <EditFormSettings>
                <EditColumn></EditColumn>
            </EditFormSettings>
        </MasterTableView>
    </telerik:RadGrid>

    <div style="margin-top: 20px">
        <label for="txtMaxAttempts">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Max Failed Login Attempts:</label>
        <asp:TextBox ID="txtMaxAttempts" runat="server" Text="5"></asp:TextBox>
        <asp:Button ID="btnSaveAttempts" runat="server" Text="Save" OnClick="btnSaveAttempts_Click" CssClass="mb-4" />
        <asp:Label ID="lblSaveStatus" runat="server" ForeColor="Green" Visible="False"></asp:Label>
    </div>


    <asp:SqlDataSource ID="UserDataSource" runat="server" ConnectionString="<%$ ConnectionStrings:InternSmallHospitalConnectionString %>"
        SelectCommand="SELECT * FROM UserInfoView"
        InsertCommand="INSERT INTO [User] ([Username], [PasswordHash], [FullName], [Email], [Phone], [RoleID], [CreatedAt], [IsLocked]) VALUES (@Username, @PasswordHash, @FullName, @Email, @Phone, @RoleID, @CreatedAt, @IsLocked)"
        UpdateCommand="UPDATE [User] SET [Username] = @Username, [PasswordHash] = @PasswordHash, [FullName] = @FullName, [Email] = @Email, [Phone] = @Phone, [RoleID] = @RoleID, [IsLocked] = @IsLocked WHERE [UserID] = @original_UserID"
        DeleteCommand="UPDATE [User] SET [IsDeleted] = 1, [DeletedBy] = @DeletedBy, [DeletedAt] = GETDATE() WHERE [UserID] = @original_UserID">

        <DeleteParameters>
            <asp:Parameter Name="original_UserID" Type="Int32" />
            <asp:Parameter Name="DeletedBy" Type="Int32" />
        </DeleteParameters>
        <InsertParameters>
            <asp:Parameter Name="Username" Type="String" />
            <asp:Parameter Name="PasswordHash" Type="String" />
            <asp:Parameter Name="FullName" Type="String" />
            <asp:Parameter Name="Email" Type="String" />
            <asp:Parameter Name="Phone" Type="String" />
            <asp:Parameter Name="RoleID" Type="Int32" />
            <asp:Parameter Name="CreatedAt" Type="DateTime" />
            <asp:Parameter Name="IsLocked" Type="Boolean" />
        </InsertParameters>
        <UpdateParameters>
            <asp:Parameter Name="Username" Type="String" />
            <asp:Parameter Name="PasswordHash" Type="String" />
            <asp:Parameter Name="FullName" Type="String" />
            <asp:Parameter Name="Email" Type="String" />
            <asp:Parameter Name="Phone" Type="String" />
            <asp:Parameter Name="RoleID" Type="Int32" />
            <asp:Parameter Name="IsLocked" Type="Boolean" />
            <asp:Parameter Name="original_UserID" Type="Int32" />
        </UpdateParameters>
    </asp:SqlDataSource>

    <asp:SqlDataSource ID="RoleDataSource" runat="server" ConnectionString="<%$ ConnectionStrings:InternSmallHospitalConnectionString %>"
        SelectCommand="SELECT RoleID, RoleName FROM Role"></asp:SqlDataSource>
</asp:Content>
