//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientHistory
    {
        public int PatientID { get; set; }
        public string FullName { get; set; }
        public int BillingID { get; set; }
        public decimal TotalAmount { get; set; }
        public decimal AmountPaid { get; set; }
        public Nullable<System.DateTime> BillingDate { get; set; }
        public string PaymentStatus { get; set; }
        public int AppointmentID { get; set; }
        public System.DateTime AppointmentDate { get; set; }
        public int DoctorID { get; set; }
        public string DoctorName { get; set; }
        public string DepartmentName { get; set; }
    }
}
