//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_AppointmentsByStaff
    {
        public string Staff { get; set; }
        public Nullable<int> HandledAppointments { get; set; }
        public Nullable<System.DateTime> AppointmentDate { get; set; }
    }
}
